name: Run Robot Framework Tests
run-name: On Push - Robot Tests
on: [push, pull_request]

jobs:
  robot-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager

      - name: Debug - List project structure
        run: |
          ls -R
          pwd

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run Robot Framework tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          robot --variable BROWSER:headlesschrome \
                --variable WINDOW_WIDTH:1920 \
                --variable WINDOW_HEIGHT:1080 \
                -d ./logs Testes/Actions.robot

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: ./logs
          retention-days: 2

      - name: Generate test report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: ./logs
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: true
